version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  lint-and-test:
    docker:
      - image: 'cimg/node:14.19-browsers'
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install:
          node-version: '14.19'
          install-yarn: true
          yarn-version: '1.22.19'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: |
            yarn lint
            yarn test
          name: linting and testing
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '14.19'
          install-yarn: true
          yarn-version: '1.22.19'
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
workflows:
  test:
    when:
      matches:
        pattern: '^dev-.+'
        value: << pipeline.git.branch >>
    jobs:
      - lint-and-test
  build-lib:
    when:
      equal: [ staging, << pipeline.git.branch >> ]
    jobs:
      - build
