version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  prepare-and-test:
    docker:
      - image: 'cimg/node:14.19-browsers'
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install:
          node-version: '14.19'
          install-yarn: true
          yarn-version: '1.22.19'
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test
workflows:
  test:
    jobs:
      - prepare-and-test:
        filters:
          branches:
            only: develop
