name: "npm publish"

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      # Build
      - uses: actions/setup-node@master
      - name: Build library
        run: yarn install && yarn build:lib-prod

      # Publish to npm
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: tendcent
      - name: Publish library to npm registry
        run: npm publish dist/macto/ngx-simple-logger --@tendcent:registry=https://registry.npmjs.org/ --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
